### ISSUE TITLE
Add inline sourcemaps option to TS compilation 

### ISSUE THREAD

**Issue by friuns2** [playcanvas/playcanvas-editor-ts-template#4]
Is it possible to debug ts playcanvas game with breakpoints?

**Comment by yaustar** [comment]
By default, inlineSourceMap and inlineSources are true in the tsconfig.json so the sourcemap is inlined to the built JS file

So yes, you can add breakpoints to TS source in devtools
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/16639049/186700324-bc767da9-524f-49c2-9714-a09c822e196d.png">

I'm going to make a change to the project so there's debug and production config files to use so that a final build without source maps can be created

**Comment by yaustar** [comment]
Fixed as of #5
